app {
  name = "graphrag"
  description = "Base configuration for GraphRAG service"

  index {
//    source = "C:/Users/Simba/IdeaProjects/CS441_HW3/input/retrieval_index"
//      source = "s3://retrieval-index-chinomona/retrieval_index/"
    source = "file:/mnt/c/Users/Simba/IdeaProjects/CS441_HW3/input/retrieval_index"

    format = "parquet"
  }

  output {
    base_path = "s3://retrieval-index-chinomona/retrieval_index/out"
  }

  Neo4jConfig {
    uri: "bolt://localhost:7687"
    user: "neo4j"
    password: "password"
    database: "neo4j"
  }

  models.ollama {
    baseUrl    = "http://127.0.0.1:11434"
    connectMs  = 30000   # 30s connect timeout
    readMs     = 180000  # 180s read timeout for big contexts
    attempts = 3
    chatModel = "llama3.2:3b"
    num_ctx    = 1024   # allow bigger context window
    temperature= 0.0
    top_p      = 0.95
    maxModelContextBlock = 2048
  }

}
