app {
  name = "graphrag"
  description = "Base configuration for GraphRAG service"

  index {
//    source = "C:/Users/Simba/IdeaProjects/CS441_HW3/input/retrieval_index"
      source = "s3://retrieval-index-chinomona/retrieval_index/"
    format = "parquet"
  }

  output {
    base_path = "s3://retrieval-index-chinomona/retrieval_index/out"
  }

  Neo4jConfig {
    uri: "bolt://localhost:7687"
    user: "neo4j"
    password: "password"
    database: "neo4j"
  }

}
